# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d3da995c5d797611f11a99ad3ea685706468f62e3e8e8e246efc760676bcbc49562171b93c1aa685d5bdbec4c8fb62c4c09ad1fee242698499c149daa599ad

test:
  secret_key_base: 08d927a1fa11ff84bfb381405dafbb234e8a26f5067e275f83bc71c0d7afd91ab607b81bb7a3aae1e89bac1116178df5d9cbb745f5b42632f6f16a4b576b7fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
